seed: 1
env_suffix: null
vis_interval: 1
save_dir: ./models
num_bptt_steps: 5
num_meta_runs: 10000
meta_optim_lr: 0.001
meta_optim_grad_clip: 1
run_non_meta_baseline: True
meta_optimizer_cfg:
    num_layers: 2
    hidden_size: 20
    lr_range: [0.00000000001, 0.00001]              # [1e-10, 1e-5]
    lr_mom_logit_init: 3.2
    optim_func: SGD
num_epochs: 50
num_ave_grad: 1                                     # average the gradient every num_ave_grad iterations
data_cfg:
    seq_name: bear                                # [train_seqs, test_seqs, blackswan, ...]
    random_train_transform: True
    batch_sizes:
        train: 1
        meta: 1
    shuffles:
        train: True
        meta: False
