seed: 1
# number of random samples [seq, train_frame_id, meta_frame_id] used for collecting gradients for a single meta update.
meta_batch_size: 4
# each sample in the meta batch starts a meta process
num_meta_processes_per_gpu: 1
# each dataset with eval=True starts a eval process
# if null assigns a GPU per eva process
num_eval_gpus: null
no_vis: False
vis_interval: 10
env_suffix: null
# saves training in '{save_dir}/{env_suffix}'
save_dir: models
resume_meta_run_epoch_mode: null        # [None, BEST_VAL, LAST]
# increases seed random seed after each meta run. supposed to enrich the training and improve generalization.
increase_seed_per_meta_run: True
random_frame_transform_per_task: True
multi_step_bptt_loss: False             # [0.05,0.10,0.2,0.30,0.35]
# sample random meta frames from epsilon range around train frame
random_frame_epsilon: null
random_object_id_sub_group: False
# if meta_optim_cfg.lr_per_tensor=False meta learning is done for a single epoch and num_epochs is only evaluated
num_epochs:
    train: 5
    eval: 10
bptt_epochs: 5
# number of frames after which the model is fine-tuned (on the first frame) again.
# only for evaluation.
# choose uneven frames to have meta matching frame in the middle of eval frame interval.
eval_online_adapt:
    step: null
    reset_model_mode: FIRST_STEP             # [None, FIRST_STEP, FULL]
    num_epochs: 10
    min_prop: 0.5
meta_optim_model_file: null
meta_optim_cfg:
    lr_hierarchy_level: NEURON               # [PARAM, NEURON, TENSOR]
    init_lr: 0.001
    learn_model_init: True
    second_order_gradients: False
    use_log_init_lr: False
    max_lr: null
meta_optim_optim_cfg:
    model_init_lr: 0.00001
    log_init_lr_lr: 0.00001
    lr: 0.001
    freeze_encoder: False
    grad_clip: null
    model_init_weight_decay: 0.001
# evalute all datasets
eval_datasets: True
# evaluation is done on all datasets
datasets:
    # meta train dataset
    train:
        name: DAVIS-2016
        split: train_seqs
        eval: True
    val:
        name: DAVIS-2016
        split: val_seqs
        eval: True
    test:
        name: DAVIS-2016
        split: null
        eval: False
# DeepLabV3 and DeepLabV3Plus loss function
loss_func: dice
parent_model:
    architecture: MaskRCNN # ['MaskRCNN', 'DeepLabV3', 'DeepLabV3Plus']
    train_encoder: True
    batch_norm:
        accum_stats: False
        learn_weight: False
        learn_bias: False
    replace_batch_with_group_norms: True
    decoder_norm_layer: GroupNorm   # ['GroupNorm', 'BatchNorm2d']
    eval_augment_rpn_proposals_mode: EXTEND   # [None, EXTEND, REPLACE]
    roi_pool_output_sizes:
        box: 7
        mask: 28
    maskrcnn_loss: LOVASZ  #[BCE, LOVASZ]
    box_nms_thresh: 0.5
    encoder: resnet50 # [resnet50, resnet101]
    train:
        paths: []
        val_split_files:
            - data/DAVIS-2017/train_val_seqs.txt
    val:
        paths: []
        val_split_files:
            - data/DAVIS-2017/train_val_seqs.txt
    test:
        paths: []
        val_split_files:
            - data/DAVIS-2017/test-dev_seqs.txt
train_early_stopping_cfg:
    patience: null
    min_loss_improv: 0.001
single_obj_seq_mode: KEEP                           # [KEEP, IGNORE, AUGMENT]
random_flip_label: False
random_no_label: False
random_box_coord_perm: False
# [train_seqs, test_seqs, blackswan, ...]

# meta refers to the test frames used to update the
# model initialization and learning rates. test refers
# to the frames used for testing during evaluation.
data_cfg:
    multi_object: False
    random_train_transform: False
    num_workers: 0
    pin_memory: False
    normalize: False
    full_resolution: False
    # integer or str for frame mode, e.g., 'random', 'middle'
    frame_ids:
        train: 0
        test: null
        meta: null
    batch_sizes:
        # train applies an epoch sampler. frame_id will be repeated bach_size times.
        train: 1
        test: 1
        # larger meta batch size will reduce number of possible bptt_epochs (GPU limits)
        meta: 1
    shuffles:
        train: True
        test: False
        meta: False
    crop_sizes:
        train: null
        test: null
        meta: null
