seed: 1
env_suffix: null
vis_interval: 1
save_img_and_eval: False                                    # save segmentation results as img in parent_model directory
parent_model_cfg:
    base_path: models/UNET_ResNet18
    split_model_path:
        - UNET_ResNet18_epoch-240.pth
        # - train_split_1_train/UNET_ResNet18_epoch-20.pth
        # - train_split_2_train/UNET_ResNet18_epoch-20.pth
        # - train_split_3_train/UNET_ResNet18_epoch-20.pth
optim_cfg:
    file_dir: models/meta/meta_run_78.model
    lr: 0.0                                        # 1e-5
    wd: 0.0
    mom: 0.0
validate_best_epoch: False
num_epochs: null
train_early_stopping:
    patience: null
    min_loss_improv: 100
num_ave_grad: 1                                     # average the gradient every num_ave_grad iterations
data:
    seq_name: train_seqs                            # [train_seqs, test_seqs, blackswan, ...]
    random_train_transform: True
    frame_ids:
        train: 0
        test: null
    batch_sizes:
        train: 1
        test: 1
    shuffles:
        train: True
        test: False
