parent_model_cfg:
    base_path: models/VGG
    split_model_path:
        - VGG_epoch-240.pth
    split_val_file_path:
        - data/DAVIS-2016/test_seqs.txt
optim_cfg:
    file_dir: null
    lr: 0.00000001                              # 1e-8
    wd: 0.0002
    mom: 0.9
num_epochs: 2000
data:
    batch_sizes:
        train: 5
