seed: 1
env_suffix: null
vis_interval: 1
parent_model:
    # base_path: models/FPN_ResNet34_group_norm
    base_path: models/FPN_ResNet34_batch_norm_fix
    val:
        paths:
        #    - train_seqs/FPN_ResNet34_group_norm_epoch-455.pth
           - train_seqs/FPN_ResNet34_batch_norm_fix_epoch-75.pth
        val_split_files:
            - data/DAVIS-2016/test_seqs.txt
optim_cfg:
    file_dir: models/meta/meta_run_78.model
    lr: 0.00001                                          # 1e-5
loss_func: dice                                       # ['cross_entropy', 'dice']
validate_inter: False
num_epochs: null
train_early_stopping:
    patience: null
    min_loss_improv: 0
dataset: train_seqs                              # [train_seqs, test_seqs, blackswan, ...]
data_cfg:
    root_dir: data/DAVIS-2016
    random_train_transform: True
    frame_ids:
        train: 0
        test: null
    batch_sizes:
        train: 8
        test: 8
    shuffles:
        train: True
        test: False
